### PR TITLE
allow grayscale input images

### PR DESCRIPTION
**Pull request by trobro**
The application crashed for me when I tried using grayscale images as input (I'm using OpenCV 3.0, haven't tried with OpenCV 2.4.x).

This small change allows grayscale images to be used as input.

### CODE REVIEW

**Comment by gnebehay** [comment]
Strange, the OpenCV api documentation states that imread by default converts all grayscale images to color images on read. Would you mind to send me your input data to reproduce this?

**Comment by trobro** [comment]
No problem, you can try with these grayscale PNG files:

http://solati.se/im.zip

cv::imread will output color images by default, but I wasn't using the challenge mode, I was simply giving the path to the first image as input to cmt. The VideoCapture object will then automatically read all of the images in the sequence, like this:

```
frame = cvLoadImage(str, CV_LOAD_IMAGE_ANYDEPTH | CV_LOAD_IMAGE_ANYCOLOR);
```

**Comment by gnebehay** [comment]
oh, I didn't know that VideoCapture was capable of reading images as well. Nice!

**Comment by gnebehay** [comment]
thanks!

**Pull request merged**
